### ISSUE TITLE
Links from email to committess with no contributions is 404

### ISSUE THREAD

**Issue by ckingbailey** [openoakland/disclosure-alert#35]
Some links from the alert email for committees that have filed a 410 Statement of Organization point to committee pages on the website that do not exist. It's unclear to me why the pages do not exist. Could it be because they don't have any contributions yet? Some committees without contributions do have pages on opendisclosure.io, such as Elias Ferran's https://www.opendisclosure.io/committee/1426949/. Is it because the committees are brand new, rather than carried over from a previous year? Marchon Tatmon has run before, but his committee page is 404.

This issue is not critical, but probably looks bad to users. The solution might not belong to this repo but instead to one of the Open Disclosure website repos.

Example from yesterday's alert email: https://www.opendisclosure.io/committee/1427385/, Faye Taylor City Council District 3

**Comment by tdooner** [comment]
Should be fixed by #38!
